# Generated by Django 4.0.4 on 2022-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='classe_viagem',
            field=models.CharField(choices=[('ECONOMICA', 'Econômica'), ('EXECUTIVA', 'Executiva'), ('PRIMEIRA_CLASSE', 'Primeira Classe')], default=0, max_length=15),
        ),
    ]
